### Get All Users
GET http://localhost:3000/api/users

### Get Single User
GET http://localhost:3000/api/users/64e6b8c5e22de0715fab8c42

### Create User
POST http://localhost:3000/api/users
Content-Type: application/json

{
  "firstName": "Karson",
  "lastName": "Kelley",
  "pronouns": "he",
  "gender": "dude",
  "email": "karson@email.com",
  "strength": 10,
  "speed": 10,
  "stamina": 10,
  "rizz": 10,
  "swag": 10,
  "magic": 10,
  "stealth": 10,
  "health": 10,
  "kd": 3.79,
  "ratedBy": 0,
  "rated": 0
}

### Update User
PUT http://localhost:3000/api/users/64e6b90de22de0715fab8c46
Content-Type: application/json

{
  "firstName": "Karson",
  "lastName": "Kelley",
  "email": "karson@email.com",
  "strength": 10,
  "speed": 9,
  "stamina": 10,
  "rizz": 10,
  "magic": 10,
  "stealth": 10,
  "health": 10,
  "kd": 3.79,
  "ratedBy": 0,
  "rated": 0
}

### Delete User
DELETE http://localhost:3000/api/users/64c2a9e1f16fda60497216f7